stages:
  - build-frontend
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com/huggias/appstarter

build-frontend:
  image: node:16.13.2
  stage: build-frontend
  script:
    - cd frontend
    - npm install
    - npm run build

build:
  stage: build
  image: gradle:latest
  script:
    - cd server
    - gradle build
  artifacts:
    paths:
      - server/build/libs/*.jar
  only:
    - tags

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_REGISTRY:$CI_COMMIT_TAG .
    - docker push $DOCKER_REGISTRY:$CI_COMMIT_TAG
  only:
    - tags