version: "3"

services:
  myapp:
    image: myapp
    ports:
      - "8081:8081"
    environment:
      - DB_URL=host.docker.internal
      - DB_USERNAME=root
      - DB_NAME=diseño_experiencia_usuario
