spring:
  datasource:
    url: jdbc:mariadb://${DB_URL:localhost}:3306/${DB_NAME:diseño_experiencia_usuario}
    username: ${DB_USERNAME:root}
  liquibase:
    change-log: classpath:db/changelog-root.json

server:
  port: 8081
  servlet:
    session:
      timeout: 30m

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
